// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXbo6VKI96nSp166Ro7yczjjLnXCBtQkg',
    appId: '1:889461080313:web:4b8465926d681e2012e228',
    messagingSenderId: '889461080313',
    projectId: 're3ayty-1fbb5',
    authDomain: 're3ayty-1fbb5.firebaseapp.com',
    storageBucket: 're3ayty-1fbb5.firebasestorage.app',
    measurementId: 'G-MK5LH81T4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMtaZsTXbR1degPg_h-iAJ5dOqEJIgnE',
    appId: '1:889461080313:android:e5bd572036e0d2aa12e228',
    messagingSenderId: '889461080313',
    projectId: 're3ayty-1fbb5',
    storageBucket: 're3ayty-1fbb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6yQ_r9NRN5YYb0SGHokpTPA28Dj1tZk',
    appId: '1:889461080313:ios:4cba7caefd52f8c812e228',
    messagingSenderId: '889461080313',
    projectId: 're3ayty-1fbb5',
    storageBucket: 're3ayty-1fbb5.firebasestorage.app',
    iosBundleId: 'com.example.hcsGradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6yQ_r9NRN5YYb0SGHokpTPA28Dj1tZk',
    appId: '1:889461080313:ios:4cba7caefd52f8c812e228',
    messagingSenderId: '889461080313',
    projectId: 're3ayty-1fbb5',
    storageBucket: 're3ayty-1fbb5.firebasestorage.app',
    iosBundleId: 'com.example.hcsGradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXbo6VKI96nSp166Ro7yczjjLnXCBtQkg',
    appId: '1:889461080313:web:b835111824c3df5812e228',
    messagingSenderId: '889461080313',
    projectId: 're3ayty-1fbb5',
    authDomain: 're3ayty-1fbb5.firebaseapp.com',
    storageBucket: 're3ayty-1fbb5.firebasestorage.app',
    measurementId: 'G-G7CY6NKB48',
  );
}
